import JSZip from 'jszip';
import { Midi } from '@tonejs/midi';
import { ExportPackData } from '../types';

export async function generateExportPack(data: ExportPackData): Promise<Blob> {
  const zip = new JSZip();

  // 1. JSON Data
  zip.file("analysis.json", JSON.stringify(data.analysis, null, 2));
  zip.file("recipe_candidates.json", JSON.stringify(data.recipes, null, 2));

  // 2. MIDI Files
  const midiFolder = zip.folder("midi");
  
  // Drums MIDI (Kick on every beat, Hats on 16ths)
  const drumsMidi = new Midi();
  const drumTrack = drumsMidi.addTrack();
  drumTrack.name = "Drums";
  
  // Kick
  for (let i = 0; i < 16; i++) { // 16 beats (4 bars)
    drumTrack.addNote({
      midi: 36, // C1
      time: i * (60 / data.analysis.bpm),
      duration: 0.1,
      velocity: 0.9
    });
  }
  // Hats
  for (let i = 0; i < 64; i++) { // 16th notes for 4 bars
    drumTrack.addNote({
      midi: 42, // F#1
      time: i * (60 / data.analysis.bpm) / 4,
      duration: 0.05,
      velocity: i % 4 === 0 ? 0.7 : 0.4 // Accent on beats
    });
  }
  if (midiFolder) midiFolder.file("drums.mid", drumsMidi.toArray());

  // Bass MIDI (Offbeat 8th notes)
  const bassMidi = new Midi();
  const bassTrack = bassMidi.addTrack();
  bassTrack.name = "Bass";
  const rootNote = 41; // F2 (default) - could parse keyCandidate
  
  for (let i = 0; i < 32; i++) { // 8th notes
    if (i % 2 !== 0) { // Offbeats
        bassTrack.addNote({
            midi: rootNote,
            time: i * (60 / data.analysis.bpm) / 2,
            duration: 0.2,
            velocity: 0.8
        });
    }
  }
  if (midiFolder) midiFolder.file("bass.mid", bassMidi.toArray());

  // Synth MIDI (Chord stabs)
  const synthMidi = new Midi();
  const synthTrack = synthMidi.addTrack();
  synthTrack.name = "Synth";
  // F Minor Triad: F3, Ab3, C4
  const chord = [53, 56, 60]; 
  
  for (let i = 0; i < 2; i++) { // Every 2 bars
    const time = i * 2 * (60 / data.analysis.bpm) * 4; // 2 bars * 4 beats
    chord.forEach(note => {
        synthTrack.addNote({
            midi: note,
            time: time,
            duration: 0.5,
            velocity: 0.7
        });
    });
  }
  if (midiFolder) midiFolder.file("synth.mid", synthMidi.toArray());

  // 3. README
  const readme = `
Music Track Deterministic Rebuilder - Export Pack
=================================================

Contents:
- analysis.json: Detailed analysis data (beat grid, segments, features).
- recipe_candidates.json: Sound design suggestions based on the audio analysis.
- midi/: Generated MIDI clips to jumpstart your remix/rebuild.

Instructions:
1. Drag the MIDI files into your DAW (e.g., Ableton Live).
2. Use the recipes in recipe_candidates.json to select stock devices and settings.
3. Layer your own samples or synths using the MIDI patterns.

Generated by Music Track Deterministic Rebuilder (MVP).
  `;
  zip.file("README.txt", readme);

  return await zip.generateAsync({ type: "blob" });
}
